name: draggable_bottom_sheet_nullsafety
description: This is a bottom sheet that is partially visible onto the screen and can be dragged from there into the screen to occupy the fullscreen.
version: 1.0.2
homepage: https://github.com/stelynx/draggable_bottom_sheet
repository: https://github.com/stelynx/draggable_bottom_sheet

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
